name = "agents-market-backend"
main = "src/index.ts"
compatibility_date = "2025-07-18"
 
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "market-api.singulay.online/*", zone_name = "singulay.online" }
]
